# Generated by Django 2.1.7 on 2019-09-16 21:53

from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logotipo', models.ImageField(upload_to='images/<django.db.models.fields.CharField>', verbose_name='Logotipo')),
                ('descripcion', models.CharField(max_length=250)),
                ('recomendacion', models.CharField(max_length=250)),
                ('descuento_popeyes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pago_conductores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('telefono', models.CharField(max_length=100)),
                ('marcador_mapa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesEstabecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenes', models.ImageField(upload_to=restaurants.models.get_image_filename, verbose_name='Imagen')),
                ('establecimiento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Establecimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=150)),
                ('telefono', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Tipo_Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='id_tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Tipo_Usuario'),
        ),
    ]
