# Generated by Django 2.2.4 on 2019-09-30 20:30

from django.db import migrations, models
import django.db.models.deletion
import restaurants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(default=1)),
                ('comentario', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=50)),
                ('codigo_activacion', models.CharField(max_length=6)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('pais', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logotipo', models.ImageField(upload_to=restaurants.models.UploadToPathAndRename('Logotipos'))),
                ('descripcion', models.CharField(max_length=250)),
                ('recomendacion', models.CharField(max_length=250)),
                ('foto_1', models.ImageField(blank=True, upload_to=restaurants.models.UploadToPathAndRename('Foto1'))),
                ('foto_2', models.ImageField(blank=True, upload_to=restaurants.models.UploadToPathAndRename('Foto2'))),
                ('foto_3', models.ImageField(blank=True, upload_to=restaurants.models.UploadToPathAndRename('Foto3'))),
                ('foto_4', models.ImageField(blank=True, upload_to=restaurants.models.UploadToPathAndRename('Foto4'))),
                ('foto_5', models.ImageField(blank=True, upload_to=restaurants.models.UploadToPathAndRename('Foto5'))),
                ('foto_6', models.ImageField(blank=True, upload_to=restaurants.models.UploadToPathAndRename('Foto6'))),
                ('foto_7', models.ImageField(blank=True, upload_to=restaurants.models.UploadToPathAndRename('Foto7'))),
                ('foto_8', models.ImageField(blank=True, upload_to=restaurants.models.UploadToPathAndRename('Foto8'))),
                ('foto_9', models.ImageField(blank=True, upload_to=restaurants.models.UploadToPathAndRename('Foto9'))),
                ('foto_10', models.ImageField(blank=True, upload_to=restaurants.models.UploadToPathAndRename('Foto10'))),
                ('descuento_popeyes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pago_conductores', models.DecimalField(decimal_places=2, max_digits=5)),
                ('telefono', models.CharField(max_length=100)),
                ('horario_lunes', models.CharField(max_length=100)),
                ('horario_martes', models.CharField(max_length=100)),
                ('horario_miercoles', models.CharField(max_length=100)),
                ('horario_jueves', models.CharField(max_length=100)),
                ('horario_viernes', models.CharField(max_length=100)),
                ('horario_sabado', models.CharField(max_length=100)),
                ('horario_domingo', models.CharField(max_length=100)),
                ('marcador_mapa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comida', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compania', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_establecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_establecimiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=50)),
                ('id_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Establecimiento')),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Tipo_usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Super_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=50)),
                ('id_tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('respuesta', models.CharField(max_length=250)),
                ('id_calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Calificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Log_saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('monto_transferido', models.DecimalField(decimal_places=2, max_digits=7)),
                ('id_usuario_recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Usuario')),
                ('id_usuario_transfiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Super_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Log_operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad_procesada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad_usuario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad_popeye', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Establecimiento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Log_conver_uc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.CharField(max_length=250)),
                ('id_usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='restaurants.Conductor')),
                ('id_usuario_remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='restaurants.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Log_conver_cu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.CharField(max_length=250)),
                ('id_usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='restaurants.Usuario')),
                ('id_usuario_remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='restaurants.Conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Log_codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('codigo_generado', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('cantidad_cuenta', models.DecimalField(decimal_places=2, max_digits=7)),
                ('id_establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Establecimiento')),
                ('id_usuario_genera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Conductor')),
                ('id_usuario_recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipo_comida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Tipo_comida'),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='tipo_establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Tipo_establecimiento'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='id_tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Tipo_usuario'),
        ),
        migrations.AddField(
            model_name='conductor',
            name='tipo_compania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Tipo_compania'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='id_establecimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Establecimiento'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Conductor'),
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=50)),
                ('archivo_key', models.FileField(upload_to='documents/')),
                ('archivo_cot', models.FileField(upload_to='documents/')),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Tipo_banco')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Conductor')),
            ],
        ),
    ]
