# Generated by Django 2.1.7 on 2019-10-05 02:00

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='logotipo',
            field=models.ImageField(upload_to=restaurants.models.UploadToPathAndRename('Logotipo')),
        ),
    ]
